# Generated by Django 3.0.6 on 2020-06-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_language_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='languages-img'),
        ),
    ]
