# Generated by Django 3.0.6 on 2020-06-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_year_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Publication_date',
            field=models.DateField(blank=True, help_text='format: yyyy-mm-dd', null=True),
        ),
    ]
