# Generated by Django 3.0.6 on 2020-06-25 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200625_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Publication_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
