# Generated by Django 3.0.6 on 2020-06-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200625_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Publication_date',
            field=models.DateField(default='2020-12-31'),
        ),
    ]
